import {createServerFn} from '@tanstack/react-start';
import {z} from 'zod';
import {requireSupabaseAuth} from '@/integrations/supabase/auth-middleware';

const statusSchema=z.enum(['New Enquiry','Contacted','Appointment Requested','Booked','Closed']);
async function requireAdmin(context:{supabase:any;userId:string}){const {data,error}=await context.supabase.from('user_roles').select('role').eq('user_id',context.userId).eq('role','admin').maybeSingle();if(error||!data)throw new Error('Administrator access required.');}
export const listEnquiries=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{await requireAdmin(context);const {data,error}=await context.supabase.from('enquiries').select('id,reference_code,name,mobile,email,city,preferred_locality,scan_type,preferred_date,notes,status,created_at').order('created_at',{ascending:false}).limit(200);if(error)throw new Error('Could not load enquiries.');const {data:uploads}=await context.supabase.from('enquiry_uploads').select('id,enquiry_id,file_name,storage_path');return {enquiries:data??[],uploads:uploads??[]};});
export const updateEnquiryStatus=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input)=>z.object({id:z.string().uuid(),status:statusSchema}).parse(input)).handler(async({data,context})=>{await requireAdmin(context);const {error}=await context.supabase.from('enquiries').update({status:data.status}).eq('id',data.id);if(error)throw new Error('Could not update the enquiry.');return {ok:true};});
export const getPrescriptionLink=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator((input)=>z.object({path:z.string().min(3).max(500)}).parse(input)).handler(async({data,context})=>{await requireAdmin(context);const {data:record,error:recordError}=await context.supabase.from('enquiry_uploads').select('id').eq('storage_path',data.path).maybeSingle();if(recordError||!record)throw new Error('Document not found.');const {data:signed,error}=await context.supabase.storage.from('prescriptions').createSignedUrl(data.path,300);if(error||!signed)throw new Error('Could not open the document.');return {url:signed.signedUrl};});
export const listTherapyManagement=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{await requireAdmin(context);const [{data:therapies,error},{data:availability},{data:prices}]=await Promise.all([context.supabase.from('nuclear_medicine_therapies').select('id,slug,name,published,featured,clinical_reviewer,clinical_reviewed_at,updated_at').order('display_order'),context.supabase.from('therapy_centre_availability').select('id,therapy_id,centre_name,city,locality,confirmed,published'),context.supabase.from('therapy_prices').select('id,therapy_id,centre_name,city,pricing_basis,price_min_inr,price_max_inr,verified,published,valid_until')]);if(error)throw new Error('Could not load therapy content.');return{therapies:therapies??[],availability:availability??[],prices:prices??[]}});
export const updateTherapyPublication=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>z.object({id:z.string().uuid(),published:z.boolean()}).parse(input)).handler(async({data,context})=>{await requireAdmin(context);const{error}=await context.supabase.from('nuclear_medicine_therapies').update({published:data.published}).eq('id',data.id);if(error)throw new Error('Could not update therapy publication.');return{ok:true}});
