export const cities = ["Delhi", "Gurgaon", "Noida", "Greater Noida", "Faridabad", "Ghaziabad"] as const;
export const citySlugs: Record<string,string> = {delhi:"Delhi",gurgaon:"Gurgaon",noida:"Noida","greater-noida":"Greater Noida",faridabad:"Faridabad",ghaziabad:"Ghaziabad"};
export const finalPriceDisclaimer = "Final price may vary by scan protocol, contrast or tracer requirement, city, centre and appointment availability.";
export const topScanDeals = [
 {name:"MRI Scan",price:"₹1,999",savings:"Preferential rate",location:"Delhi NCR",modality:"mri-scan"},
 {name:"CT Scan",price:"₹999",savings:"Preferential rate",location:"Delhi NCR",modality:"ct-scan"},
 {name:"PET-CT Scan",price:"₹9,999",savings:"Preferential rate",location:"Delhi NCR",modality:"pet-ct-scan"},
 {name:"PSMA PET-CT",price:"Special patient rates available",savings:"Centre-specific savings",location:"Delhi NCR",modality:"pet-ct-scan"},
 {name:"Ultrasound",price:"₹499",savings:"Preferential rate",location:"Delhi NCR",modality:"ultrasound"},
 {name:"Digital X-Ray",price:"₹199",savings:"Preferential rate",location:"Delhi NCR",modality:"x-ray-fluoroscopy"},
 {name:"Mammography",price:"₹999",savings:"Preferential rate",location:"Delhi NCR",modality:"mammography"},
 {name:"DEXA Bone Density Scan",price:"₹999",savings:"Preferential rate",location:"Delhi NCR",modality:"dexa-scan"},
] as const;
export const categories = [
 {name:"MRI Scan",slug:"mri-scan",short:"Detailed soft-tissue imaging without ionising radiation.",types:["Brain MRI","Spine MRI","Knee MRI","Prostate mpMRI","MRCP"]},
 {name:"CT Scan",slug:"ct-scan",short:"Fast cross-sectional imaging for a wide range of clinical questions.",types:["CT Brain","HRCT Chest","CT Angiography","CT Abdomen"]},
 {name:"Dual Energy / GSI Spectral CT",slug:"spectral-ct",short:"Advanced CT techniques for selected material and perfusion assessment.",types:["Spectral CT","Iodine Mapping","Stone Analysis"]},
 {name:"PET-CT Scan",slug:"pet-ct-scan",short:"Molecular and anatomical imaging in specialist-led care pathways.",types:["FDG PET-CT","PSMA PET-CT","DOTANOC PET-CT"]},
 {name:"PET-MRI Scan",slug:"pet-mri-scan",short:"Combined molecular imaging and MRI for selected indications.",types:["Whole-Body PET-MRI","Brain PET-MRI","PSMA PET-MRI"]},
 {name:"Gamma Camera / SPECT",slug:"gamma-camera-spect",short:"Functional nuclear medicine imaging using prescribed radiotracers.",types:["Bone Scan","DTPA Renal Scan","SPECT-CT"]},
 {name:"Ultrasound / Sonography",slug:"ultrasound",short:"Real-time sound-wave imaging for abdominal, pregnancy and vascular studies.",types:["Whole Abdomen","Pregnancy Ultrasound","Doppler"]},
 {name:"X-Ray / Fluoroscopy",slug:"x-ray-fluoroscopy",short:"Radiographic and real-time X-ray examinations.",types:["Chest X-Ray","Spine X-Ray","Fluoroscopy"]},
 {name:"DEXA Scan",slug:"dexa-scan",short:"Low-dose bone mineral density and body composition assessment.",types:["BMD Scan","Spine DEXA","Hip DEXA"]},
 {name:"Mammography",slug:"mammography",short:"Specialist breast imaging for screening and diagnostic assessment.",types:["Digital Mammography","3D Tomosynthesis","Breast Ultrasound"]},
] as const;
export const scans: Record<string,{name:string; modality:string; why:string; evaluates:string[]; prep:string; contrast:string; duration:string; price:string; safety:string}> = {
 "brain-mri":{name:"Brain MRI",modality:"mri-scan",why:"Doctors commonly advise it to evaluate symptoms or findings involving the brain and surrounding structures.",evaluates:["Brain tissue and fluid spaces","Blood vessels with added sequences","Selected nerves and nearby structures"],prep:"Remove metal items and disclose implants, devices, pregnancy, kidney concerns and claustrophobia. Fasting depends on the protocol.",contrast:"Gadolinium contrast may be advised after safety screening for selected clinical questions.",duration:"Usually 20–45 minutes",price:"₹3,500–₹8,500",safety:"MRI does not use ionising radiation. Strong magnetic fields require careful implant and metal screening."},
 "hrct-chest":{name:"HRCT Chest",modality:"ct-scan",why:"Doctors may advise HRCT to examine fine detail in lung tissue in the context of symptoms, examination and prior tests.",evaluates:["Lung tissue patterns","Airways","Selected pleural findings"],prep:"Carry prior chest imaging. Tell the centre about pregnancy or possible pregnancy. Routine non-contrast HRCT often needs no fasting.",contrast:"HRCT is commonly performed without contrast, though the prescribed protocol determines this.",duration:"Usually 10–20 minutes",price:"₹2,500–₹5,500",safety:"CT uses ionising radiation. The referring doctor and centre determine appropriateness and optimise the protocol."},
 "psma-pet-ct":{name:"PSMA PET-CT",modality:"pet-ct-scan",why:"Specialists may use PSMA-targeted imaging in selected prostate cancer care pathways, including staging or recurrence evaluation.",evaluates:["Distribution of PSMA-avid findings","Whole-body disease pattern","Findings relevant to specialist planning"],prep:"Carry pathology, PSA history, prior imaging and treatment records. Follow tracer-specific hydration and timing instructions from the centre.",contrast:"A PSMA-targeted radiotracer is administered. CT contrast may be added only when prescribed and screened.",duration:"Allow approximately 2–4 hours",price:"₹22,000–₹35,000",safety:"Uses a radiotracer and CT radiation. Final interpretation and care decisions require qualified specialist review."},
 "whole-abdomen-ultrasound":{name:"Whole Abdomen Ultrasound",modality:"ultrasound",why:"Doctors may advise it to assess abdominal organs in the context of symptoms, examination or follow-up.",evaluates:["Liver and gallbladder","Kidneys and urinary bladder","Pancreas, spleen and other visible structures"],prep:"Fasting and a full bladder are commonly requested, but instructions vary. Confirm with the centre before arrival.",contrast:"No contrast or radiotracer is usually used.",duration:"Usually 15–30 minutes",price:"₹800–₹2,500",safety:"Diagnostic ultrasound uses sound waves and does not use ionising radiation."},
};
export const centres = [
 {name:"Northstar Imaging Delhi — Demo",slug:"northstar-imaging-delhi-demo",city:"Delhi",locality:"South Delhi",tech:["3T MRI","128-slice CT"],services:["MRI","CT","Ultrasound"],turnaround:"Routine reports within 24 hours",cashless:true,open:false},
 {name:"Aravali Molecular Imaging — Demo",slug:"aravali-molecular-imaging-demo",city:"Gurgaon",locality:"Sector 44",tech:["Digital PET-CT","SPECT-CT"],services:["PET-CT","Nuclear Medicine"],turnaround:"PET reports in 24–48 hours",cashless:true,open:false},
 {name:"Yamuna Advanced Diagnostics — Demo",slug:"yamuna-advanced-diagnostics-demo",city:"Noida",locality:"Sector 62",tech:["1.5T MRI","Spectral CT","3D Mammography"],services:["MRI","CT","Mammography"],turnaround:"Routine reports often same day",cashless:false,open:true},
 {name:"NCR Scan Point — Demo",slug:"ncr-scan-point-greater-noida-demo",city:"Greater Noida",locality:"Pari Chowk",tech:["1.5T MRI","64-slice CT"],services:["MRI","CT","DEXA"],turnaround:"Routine reports within 24 hours",cashless:true,open:false},
 {name:"Crown Breast & Imaging — Demo",slug:"crown-breast-imaging-demo",city:"Faridabad",locality:"Sector 16",tech:["3D Tomosynthesis","Ultrasound","DEXA"],services:["Mammography","Breast Ultrasound"],turnaround:"Routine reports within 24 hours",cashless:false,open:false},
 {name:"Hindon Diagnostic Imaging — Demo",slug:"hindon-diagnostic-imaging-demo",city:"Ghaziabad",locality:"Indirapuram",tech:["3T MRI","128-slice CT"],services:["MRI","CT","Ultrasound"],turnaround:"Routine reports often same day",cashless:true,open:true},
] as const;
export const guides = [
 {title:"MRI versus CT Scan",slug:"mri-versus-ct-scan",type:"comparison"},{title:"PET-CT versus PET-MRI",slug:"pet-ct-versus-pet-mri",type:"comparison"},{title:"1.5T MRI versus 3T MRI",slug:"1-5t-mri-versus-3t-mri",type:"comparison"},{title:"PET-CT Cost in Delhi NCR",slug:"pet-ct-cost-delhi-ncr",type:"cost"},{title:"MRI Scan Cost in Delhi",slug:"mri-scan-cost-delhi",type:"cost"},{title:"CT Scan Cost in Delhi NCR",slug:"ct-scan-cost-delhi-ncr",type:"cost"},{title:"How to Prepare for MRI",slug:"how-to-prepare-for-mri",type:"preparation"},{title:"PET-CT Fasting Instructions",slug:"pet-ct-fasting-instructions",type:"preparation"},{title:"Radiation Safety in CT, PET-CT and X-Ray",slug:"radiation-safety-ct-pet-ct-x-ray",type:"safety"},
] as const;
