import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { MapPin, Search } from "lucide-react";
import { Breadcrumbs, CentreCards, Disclaimer, PageIntro, PriceDisclaimer } from "@/components/bookmyscan/Blocks";
import { Button } from "@/components/ui/button";
import { getCentresForLocality, getPriorityLocality } from "@/lib/catalog";

export const Route=createFileRoute("/scan-centres/$city/area/$locality")({
 loader:({params})=>{const area=getPriorityLocality(params.city,params.locality);if(!area)throw notFound();return {area,count:getCentresForLocality(area).length}},
 head:({loaderData,params})=>{const area=loaderData?.area;const title=area?`Scan Centres in ${area.name}, ${area.city==="Gurgaon"?"Gurugram":area.city} | SavoScan.com`:"Local Scan Centres | SavoScan.com";const description=area?.summary??"Compare supplied radiology centre information and request appointment assistance.";const path=`/scan-centres/${params.city}/area/${params.locality}`;return {meta:[{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{property:"og:url",content:path},{name:"twitter:card",content:"summary_large_image"},...(!area?.indexable?[{name:"robots",content:"noindex"}]:[])],links:[{rel:"canonical",href:path}],scripts:area?[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage",name:title,description,about:{"@type":"Service",serviceType:"Radiology scan comparison and appointment assistance",areaServed:[area.name,area.city]}})},{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Scan Centres",item:"https://savoscan.com/scan-centres"},{"@type":"ListItem",position:2,name:area.city,item:`https://savoscan.com/scan-centres/${area.citySlug}`},{"@type":"ListItem",position:3,name:area.name,item:`https://savoscan.com${path}`} ]})}]:[]}},
 component:LocalityPage,
});

function LocalityPage(){const {area,count}=Route.useLoaderData();const cityLabel=area.city==="Gurgaon"?"Gurugram (Gurgaon)":area.city;return <><PageIntro eyebrow="Local scan comparison" title={`${area.name}, ${cityLabel} Mein Scan Centres`} copy={area.summary}><Breadcrumbs items={[{label:"Scan Centres",to:"/scan-centres"},{label:cityLabel,to:`/scan-centres/${area.citySlug}`},{label:area.name}]}/></PageIntro><section className="section page-wrap"><div className="location-summary"><div><p className="eyebrow">Area directory</p><h2>{count} supplied {count===1?"listing":"listings"} around {area.name}</h2><p>Compare advertised scan services, then confirm the exact prescribed protocol, total price, appointment slot and address before travel.</p></div><MapPin/></div><Disclaimer/><CentreCards city={area.city} localities={area.matches} limit={20}/><div className="location-assist"><Search/><div><h2>Kya {area.name} ke Paas Dusra Centre Chahiye?</h2><p>Share the prescribed scan and preferred travel area. SavoScan can check suitable options without claiming unverified availability.</p></div><Button asChild><Link to="/book-a-scan" search={{scan:"",protocol:"",centre:"",offer:""}}>Check Scan Price</Link></Button></div><PriceDisclaimer/></section></>}