import { Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Clock3, MapPin, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { centres } from "@/lib/catalog";
export function PageIntro({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children?:React.ReactNode}){return <section className="page-hero"><div className="page-wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{copy}</p>{children}</div></section>}
export function Breadcrumbs({items}:{items:{label:string;to?:string}[]}){return <nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-xs text-muted-foreground">{items.map((i,n)=><span key={i.label} className="flex gap-2">{n>0&&<span>/</span>}{i.to?<Link to={i.to}>{i.label}</Link>:i.label}</span>)}</nav>}
export function Disclaimer({therapy=false}:{therapy?:boolean}){return <div className="disclaimer"><ShieldAlert/><p>{therapy?"Medical suitability, eligibility, treatment planning and treatment decisions are determined only by qualified treating specialists and hospitals. BookMyScan.in provides navigation and appointment assistance only.":"This information is for general awareness and appointment navigation, not self-diagnosis or a treatment recommendation. Always consult your treating doctor."}</p></div>}
export function CentreCards({city,service,openOnly=false,limit=3}:{city?:string;service?:string;openOnly?:boolean;limit?:number}){const list=centres.filter(c=>(!city||c.city===city)&&(!service||c.services.some(item=>item.toLowerCase().includes(service.toLowerCase())))&&(!openOnly||c.open)).slice(0,limit);return <div className="card-grid">{list.map(c=><article className="centre-card" key={c.slug}><div className="demo-label">Demo data — not a verified partner</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3>{c.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4"/>{c.locality}, {c.city}</p></div><BadgeCheck className="size-5 text-accent"/></div><div className="mt-4 flex flex-wrap gap-2">{c.tech.map(t=><span className="tag" key={t}>{t}</span>)}</div><p className="mt-4 flex gap-2 text-sm"><Clock3 className="mt-0.5 size-4 text-accent"/>{c.turnaround}</p><div className="mt-5 flex gap-2"><Button asChild size="sm"><Link to="/book-a-scan">Request options</Link></Button><Button asChild size="sm" variant="outline"><Link to="/scan-centres/$city/$slug" params={{city:c.city.toLowerCase().replaceAll(' ','-'),slug:c.slug}}>Profile</Link></Button></div></div></article>)}</div>}
export function SectionHead({kicker,title,copy,action}:{kicker:string;title:string;copy?:string;action?:React.ReactNode}){return <div className="section-head"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>{action}</div>}
export function StickyAssist(){return <div className="sticky-assist"><div><strong>Need help choosing the right centre?</strong><span>Share your prescription for protocol and availability assistance.</span></div><Button asChild><Link to="/book-a-scan">Request assistance <ArrowRight/></Link></Button></div>}
