import { Link } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, Clock3, IndianRupee, MapPin, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { centres, finalPriceDisclaimer, topScanDeals } from "@/lib/catalog";
export function PageIntro({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children?:React.ReactNode}){return <section className="page-hero"><div className="page-wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{copy}</p>{children}</div></section>}
export function Breadcrumbs({items}:{items:{label:string;to?:string}[]}){return <nav aria-label="Breadcrumb" className="mb-6 flex flex-wrap gap-2 text-xs text-muted-foreground">{items.map((i,n)=><span key={i.label} className="flex gap-2">{n>0&&<span>/</span>}{i.to?<Link to={i.to}>{i.label}</Link>:i.label}</span>)}</nav>}
export function Disclaimer({therapy=false}:{therapy?:boolean}){return <div className="disclaimer"><ShieldAlert/><p>{therapy?"Medical suitability, eligibility, treatment planning and treatment decisions are determined only by qualified treating specialists and hospitals. BookMyScan.in provides navigation and appointment assistance only.":"This information is for general awareness and appointment navigation, not self-diagnosis or a treatment recommendation. Always consult your treating doctor."}</p></div>}
export function PriceDisclaimer(){return <p className="price-disclaimer">{finalPriceDisclaimer}</p>}
export function TopScanDeals({compact=false}:{compact?:boolean}){return <><div className={compact?"deal-grid deal-grid-compact":"deal-grid"}>{topScanDeals.map(deal=><article className="deal-card" key={deal.name}><div className="deal-card-top"><span className="savings-badge">{deal.savings}</span><span className="verification-badge"><BadgeCheck/> Price verification pending</span></div><h3>{deal.name}</h3><div className="deal-price"><div><span>Regular / centre price</span><s>Confirmed on request</s></div><div><span>BookMyScan price</span><strong>{deal.price.startsWith("₹")?<>from {deal.price}</>:deal.price}</strong></div></div><p className="deal-location"><MapPin/>{deal.location} · locality confirmed with options</p><PriceDisclaimer/><Button asChild className="mt-5 w-full"><Link to="/book-a-scan">Check Availability <ArrowRight/></Link></Button></article>)}</div><p className="deal-note">Displayed “from” rates require centre, protocol and slot confirmation. Limited-slot labels appear only after partner verification.</p></>}
export function CentreCards({city,service,openOnly=false,limit=3}:{city?:string;service?:string;openOnly?:boolean;limit?:number}){const list=centres.filter(c=>(!city||c.city===city)&&(!service||c.services.some(item=>item.toLowerCase().includes(service.toLowerCase())))&&(!openOnly||c.open)).slice(0,limit);return <div className="card-grid">{list.map(c=><article className="centre-card" key={c.slug}><div className="demo-label">Verification pending — demo listing</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3>{c.name}</h3><p className="mt-1 flex items-center gap-1 text-sm text-muted-foreground"><MapPin className="size-4"/>{c.locality}, {c.city}</p></div><BadgeCheck className="size-5 text-muted-foreground" aria-label="Verification pending"/></div><div className="mt-4 flex flex-wrap gap-2">{c.tech.map(t=><span className="tag" key={t}>{t}</span>)}</div><p className="mt-4 flex gap-2 text-sm"><Clock3 className="mt-0.5 size-4 text-accent"/>{c.turnaround}</p><div className="listing-price"><IndianRupee/><div><span>Regular / centre price</span><strong>Confirming with centre</strong></div><div><span>BookMyScan price</span><strong>Available after scan review</strong></div><span className="savings-badge">Savings confirmed with quote</span></div><PriceDisclaimer/><div className="mt-5 flex flex-wrap gap-2"><Button asChild size="sm"><Link to="/book-a-scan">Check Availability</Link></Button><Button asChild size="sm" variant="outline"><Link to="/scan-centres/$city/$slug" params={{city:c.city.toLowerCase().replaceAll(' ','-'),slug:c.slug}}>Profile</Link></Button></div></div></article>)}</div>}
export function SectionHead({kicker,title,copy,action}:{kicker:string;title:string;copy?:string;action?:React.ReactNode}){return <div className="section-head"><div><p className="eyebrow">{kicker}</p><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>{action}</div>}
export function StickyAssist(){return <div className="sticky-assist"><div><strong>Need help choosing the right centre?</strong><span>Share your prescription for protocol and availability assistance.</span></div><Button asChild><Link to="/book-a-scan">Request assistance <ArrowRight/></Link></Button></div>}
