import { useState } from "react";
import { useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { LoaderCircle, UploadCloud } from "lucide-react";
import { createEnquiry } from "@/lib/enquiries.functions";
import { cities,categories } from "@/lib/catalog";
import { Button } from "@/components/ui/button";
export function BookingForm({defaultScan=""}:{defaultScan?:string}){const submit=useServerFn(createEnquiry);const navigate=useNavigate();const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function onSubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");const file=new FormData(e.currentTarget).get("file");if(file instanceof File&&file.size>0&&(file.size>10485760||!["application/pdf","image/jpeg","image/png"].includes(file.type))){setError("Upload a PDF, JPG or PNG up to 10 MB.");return}setBusy(true);try{const result=await submit({data:new FormData(e.currentTarget)});await navigate({to:"/booking-confirmation",search:{reference:result.reference}})}catch(err){setError(err instanceof Error?err.message:"Please try again.")}finally{setBusy(false)}}return <form onSubmit={onSubmit} className="booking-form"><div className="grid gap-5 md:grid-cols-2"><Field label="Full name" name="name" required maxLength={100}/><Field label="Mobile number" name="mobile" type="tel" required pattern="[+0-9 \u002D]{10,16}"/><Field label="Email (optional)" name="email" type="email"/><label>City<select name="city" required defaultValue=""><option value="" disabled>Select city</option>{cities.map(c=><option key={c}>{c}</option>)}</select></label><Field label="Preferred locality" name="preferredLocality" maxLength={150}/><label>Scan type<select name="scanType" required defaultValue={defaultScan}><option value="" disabled>Select scan</option>{categories.map(c=><option key={c.slug}>{c.name}</option>)}</select></label><Field label="Preferred appointment date" name="preferredDate" type="date"/><label className="upload-field"><span>Prescription / report (optional)</span><div><UploadCloud/> PDF, JPG or PNG · up to 10 MB</div><input name="file" type="file" accept="application/pdf,image/jpeg,image/png"/></label></div><label className="mt-5 block">Notes<textarea name="notes" rows={4} maxLength={2000} placeholder="Share any timing, mobility or centre preferences."/></label><input className="hidden" name="website" tabIndex={-1} autoComplete="off"/><input type="hidden" name="sourcePath" value="/book-a-scan"/><label className="consent-row"><input type="checkbox" name="consent" value="true" required/><span>I consent to BookMyScan.in using and sharing these details and uploaded records only to coordinate my scan enquiry with suitable centres. I understand it is a booking facilitator, not a medical provider.</span></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button size="lg" className="w-full md:w-auto" disabled={busy}>{busy?<><LoaderCircle className="animate-spin"/>Submitting</>:"Request appointment support"}</Button><p className="mt-3 text-xs text-muted-foreground">Do not upload unrelated identity or financial documents. Clinical safety screening and consent happen at the selected centre.</p></form>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <label>{label}<input {...rest}/></label>}
