import {useState} from "react";
import {useServerFn} from "@tanstack/react-start";
import {CheckCircle2,LoaderCircle,PhoneCall} from "lucide-react";
import {Button} from "@/components/ui/button";
import {createTherapyEnquiry} from "@/lib/therapy-enquiries.functions";
import {publishedTherapies,therapyCities} from "@/lib/therapies";
export function TherapyEnquiryForm({defaultTherapy="",sourcePath,therapySlugs}:{defaultTherapy?:string;sourcePath:string;therapySlugs?:string[]}){const submit=useServerFn(createTherapyEnquiry);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[reference,setReference]=useState("");const choices=publishedTherapies.filter(therapy=>!therapySlugs||therapySlugs.includes(therapy.slug));async function onSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");setBusy(true);try{const result=await submit({data:new FormData(event.currentTarget)});setReference(result.reference);event.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"Please try again.")}finally{setBusy(false)}}if(reference)return <div className="therapy-form-success" role="status"><CheckCircle2/><h3>Callback request received</h3><p>Your reference is <strong>{reference}</strong>. Our patient assistance team will review your request.</p></div>;return <form className="therapy-form" onSubmit={onSubmit}><div className="therapy-form-grid"><Field label="Patient or attendant name" name="name" required maxLength={100}/><Field label="Mobile number" name="mobile" type="tel" required pattern="\+?[0-9 \u002D]{10,16}"/><label>City<select name="city" required defaultValue=""><option value="" disabled>Select city</option>{therapyCities.map(city=><option key={city}>{city}</option>)}</select></label><label>Therapy of interest<select name="therapySlug" required defaultValue={defaultTherapy}><option value="" disabled>Select therapy</option>{choices.map(therapy=><option key={therapy.slug} value={therapy.slug}>{therapy.shortName}</option>)}</select></label><Field label="Preferred callback time (optional)" name="callbackTime" placeholder="For example, 4–6 PM" maxLength={100}/></div><label className="mt-5 block">Message (optional)<textarea name="message" rows={4} maxLength={1500} placeholder="Share any centre, location or estimate questions."/></label><input className="hidden" name="website" tabIndex={-1} autoComplete="off"/><input type="hidden" name="sourcePath" value={sourcePath}/><Attribution/><label className="consent-row"><input type="checkbox" name="consent" value="true" required/><span>I consent to SavoScan.com contacting me about this enquiry and sharing relevant details with suitable treatment centres for assistance. SavoScan.com is a patient assistance and booking service, not the treatment provider.</span></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button size="lg" disabled={busy}>{busy?<><LoaderCircle className="animate-spin"/>Submitting</>:<><PhoneCall/>Request a Call Back</>}</Button></form>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const{label,...rest}=props;return <label>{label}<input {...rest}/></label>}
function Attribution(){if(typeof window==="undefined")return <><input type="hidden" name="utmSource"/><input type="hidden" name="utmMedium"/><input type="hidden" name="utmCampaign"/></>;const params=new URLSearchParams(window.location.search);return <><input type="hidden" name="utmSource" value={params.get("utm_source")??""}/><input type="hidden" name="utmMedium" value={params.get("utm_medium")??""}/><input type="hidden" name="utmCampaign" value={params.get("utm_campaign")??""}/></>}
