/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdvancedCancerImagingRouteImport } from './routes/advanced-cancer-imaging'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookAScanRouteImport } from './routes/book-a-scan'
import { Route as BookingConfirmationRouteImport } from './routes/booking-confirmation'
import { Route as CompareScansRouteImport } from './routes/compare-scans'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as Lu177PsmaTherapyRouteImport } from './routes/lu-177-psma-therapy'
import { Route as NuclearMedicineTherapiesRouteImport } from './routes/nuclear-medicine-therapies'
import { Route as PreparationGuidesRouteImport } from './routes/preparation-guides'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundCancellationRouteImport } from './routes/refund-cancellation'
import { Route as ScanCentresRouteImport } from './routes/scan-centres'
import { Route as ScanCostRouteImport } from './routes/scan-cost'
import { Route as ScanTestsRouteImport } from './routes/scan-tests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as NuclearMedicineTherapiesIndexRouteImport } from './routes/nuclear-medicine-therapies.index'
import { Route as NuclearMedicineTherapiesTherapyRouteImport } from './routes/nuclear-medicine-therapies.$therapy'
import { Route as ScanCentresIndexRouteImport } from './routes/scan-centres.index'
import { Route as ScanCentresCityRouteImport } from './routes/scan-centres.$city'
import { Route as ScanTestsIndexRouteImport } from './routes/scan-tests.index'
import { Route as ScanTestsModalityRouteImport } from './routes/scan-tests.$modality'
import { Route as ScanCentresCityIndexRouteImport } from './routes/scan-centres.$city.index'
import { Route as ScanCentresCitySlugRouteImport } from './routes/scan-centres.$city.$slug'
import { Route as ScanTestsModalityIndexRouteImport } from './routes/scan-tests.$modality.index'
import { Route as ScanTestsModalityDetailRouteImport } from './routes/scan-tests.$modality.$detail'
import { Route as ScanCentresCityAreaLocalityRouteImport } from './routes/scan-centres.$city.area.$locality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedCancerImagingRoute = AdvancedCancerImagingRouteImport.update({
  id: '/advanced-cancer-imaging',
  path: '/advanced-cancer-imaging',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAScanRoute = BookAScanRouteImport.update({
  id: '/book-a-scan',
  path: '/book-a-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking-confirmation',
  path: '/booking-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareScansRoute = CompareScansRouteImport.update({
  id: '/compare-scans',
  path: '/compare-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const Lu177PsmaTherapyRoute = Lu177PsmaTherapyRouteImport.update({
  id: '/lu-177-psma-therapy',
  path: '/lu-177-psma-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const NuclearMedicineTherapiesRoute =
  NuclearMedicineTherapiesRouteImport.update({
    id: '/nuclear-medicine-therapies',
    path: '/nuclear-medicine-therapies',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreparationGuidesRoute = PreparationGuidesRouteImport.update({
  id: '/preparation-guides',
  path: '/preparation-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundCancellationRoute = RefundCancellationRouteImport.update({
  id: '/refund-cancellation',
  path: '/refund-cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCentresRoute = ScanCentresRouteImport.update({
  id: '/scan-centres',
  path: '/scan-centres',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanCostRoute = ScanCostRouteImport.update({
  id: '/scan-cost',
  path: '/scan-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanTestsRoute = ScanTestsRouteImport.update({
  id: '/scan-tests',
  path: '/scan-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConditionsRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NuclearMedicineTherapiesIndexRoute =
  NuclearMedicineTherapiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NuclearMedicineTherapiesRoute,
  } as any)
const NuclearMedicineTherapiesTherapyRoute =
  NuclearMedicineTherapiesTherapyRouteImport.update({
    id: '/$therapy',
    path: '/$therapy',
    getParentRoute: () => NuclearMedicineTherapiesRoute,
  } as any)
const ScanCentresIndexRoute = ScanCentresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanCentresRoute,
} as any)
const ScanCentresCityRoute = ScanCentresCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ScanCentresRoute,
} as any)
const ScanTestsIndexRoute = ScanTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanTestsRoute,
} as any)
const ScanTestsModalityRoute = ScanTestsModalityRouteImport.update({
  id: '/$modality',
  path: '/$modality',
  getParentRoute: () => ScanTestsRoute,
} as any)
const ScanCentresCityIndexRoute = ScanCentresCityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanCentresCityRoute,
} as any)
const ScanCentresCitySlugRoute = ScanCentresCitySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScanCentresCityRoute,
} as any)
const ScanTestsModalityIndexRoute = ScanTestsModalityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanTestsModalityRoute,
} as any)
const ScanTestsModalityDetailRoute = ScanTestsModalityDetailRouteImport.update({
  id: '/$detail',
  path: '/$detail',
  getParentRoute: () => ScanTestsModalityRoute,
} as any)
const ScanCentresCityAreaLocalityRoute =
  ScanCentresCityAreaLocalityRouteImport.update({
    id: '/area/$locality',
    path: '/area/$locality',
    getParentRoute: () => ScanCentresCityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced-cancer-imaging': typeof AdvancedCancerImagingRoute
  '/auth': typeof AuthRoute
  '/book-a-scan': typeof BookAScanRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/compare-scans': typeof CompareScansRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/grievance': typeof GrievanceRoute
  '/lu-177-psma-therapy': typeof Lu177PsmaTherapyRoute
  '/nuclear-medicine-therapies': typeof NuclearMedicineTherapiesRouteWithChildren
  '/preparation-guides': typeof PreparationGuidesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/scan-centres': typeof ScanCentresRouteWithChildren
  '/scan-cost': typeof ScanCostRoute
  '/scan-tests': typeof ScanTestsRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/nuclear-medicine-therapies/$therapy': typeof NuclearMedicineTherapiesTherapyRoute
  '/scan-centres/$city': typeof ScanCentresCityRouteWithChildren
  '/scan-tests/$modality': typeof ScanTestsModalityRouteWithChildren
  '/nuclear-medicine-therapies/': typeof NuclearMedicineTherapiesIndexRoute
  '/scan-centres/': typeof ScanCentresIndexRoute
  '/scan-tests/': typeof ScanTestsIndexRoute
  '/scan-centres/$city/$slug': typeof ScanCentresCitySlugRoute
  '/scan-tests/$modality/$detail': typeof ScanTestsModalityDetailRoute
  '/scan-centres/$city/': typeof ScanCentresCityIndexRoute
  '/scan-tests/$modality/': typeof ScanTestsModalityIndexRoute
  '/scan-centres/$city/area/$locality': typeof ScanCentresCityAreaLocalityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced-cancer-imaging': typeof AdvancedCancerImagingRoute
  '/auth': typeof AuthRoute
  '/book-a-scan': typeof BookAScanRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/compare-scans': typeof CompareScansRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/grievance': typeof GrievanceRoute
  '/lu-177-psma-therapy': typeof Lu177PsmaTherapyRoute
  '/preparation-guides': typeof PreparationGuidesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/scan-cost': typeof ScanCostRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/nuclear-medicine-therapies/$therapy': typeof NuclearMedicineTherapiesTherapyRoute
  '/nuclear-medicine-therapies': typeof NuclearMedicineTherapiesIndexRoute
  '/scan-centres': typeof ScanCentresIndexRoute
  '/scan-tests': typeof ScanTestsIndexRoute
  '/scan-centres/$city/$slug': typeof ScanCentresCitySlugRoute
  '/scan-tests/$modality/$detail': typeof ScanTestsModalityDetailRoute
  '/scan-centres/$city': typeof ScanCentresCityIndexRoute
  '/scan-tests/$modality': typeof ScanTestsModalityIndexRoute
  '/scan-centres/$city/area/$locality': typeof ScanCentresCityAreaLocalityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/advanced-cancer-imaging': typeof AdvancedCancerImagingRoute
  '/auth': typeof AuthRoute
  '/book-a-scan': typeof BookAScanRoute
  '/booking-confirmation': typeof BookingConfirmationRoute
  '/compare-scans': typeof CompareScansRoute
  '/conditions': typeof ConditionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/grievance': typeof GrievanceRoute
  '/lu-177-psma-therapy': typeof Lu177PsmaTherapyRoute
  '/nuclear-medicine-therapies': typeof NuclearMedicineTherapiesRouteWithChildren
  '/preparation-guides': typeof PreparationGuidesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-cancellation': typeof RefundCancellationRoute
  '/scan-centres': typeof ScanCentresRouteWithChildren
  '/scan-cost': typeof ScanCostRoute
  '/scan-tests': typeof ScanTestsRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/nuclear-medicine-therapies/$therapy': typeof NuclearMedicineTherapiesTherapyRoute
  '/scan-centres/$city': typeof ScanCentresCityRouteWithChildren
  '/scan-tests/$modality': typeof ScanTestsModalityRouteWithChildren
  '/nuclear-medicine-therapies/': typeof NuclearMedicineTherapiesIndexRoute
  '/scan-centres/': typeof ScanCentresIndexRoute
  '/scan-tests/': typeof ScanTestsIndexRoute
  '/scan-centres/$city/$slug': typeof ScanCentresCitySlugRoute
  '/scan-tests/$modality/$detail': typeof ScanTestsModalityDetailRoute
  '/scan-centres/$city/': typeof ScanCentresCityIndexRoute
  '/scan-tests/$modality/': typeof ScanTestsModalityIndexRoute
  '/scan-centres/$city/area/$locality': typeof ScanCentresCityAreaLocalityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced-cancer-imaging'
    | '/auth'
    | '/book-a-scan'
    | '/booking-confirmation'
    | '/compare-scans'
    | '/conditions'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/grievance'
    | '/lu-177-psma-therapy'
    | '/nuclear-medicine-therapies'
    | '/preparation-guides'
    | '/privacy'
    | '/refund-cancellation'
    | '/scan-centres'
    | '/scan-cost'
    | '/scan-tests'
    | '/terms'
    | '/admin'
    | '/conditions/$slug'
    | '/guides/$slug'
    | '/nuclear-medicine-therapies/$therapy'
    | '/scan-centres/$city'
    | '/scan-tests/$modality'
    | '/nuclear-medicine-therapies/'
    | '/scan-centres/'
    | '/scan-tests/'
    | '/scan-centres/$city/$slug'
    | '/scan-tests/$modality/$detail'
    | '/scan-centres/$city/'
    | '/scan-tests/$modality/'
    | '/scan-centres/$city/area/$locality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced-cancer-imaging'
    | '/auth'
    | '/book-a-scan'
    | '/booking-confirmation'
    | '/compare-scans'
    | '/conditions'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/grievance'
    | '/lu-177-psma-therapy'
    | '/preparation-guides'
    | '/privacy'
    | '/refund-cancellation'
    | '/scan-cost'
    | '/terms'
    | '/admin'
    | '/conditions/$slug'
    | '/guides/$slug'
    | '/nuclear-medicine-therapies/$therapy'
    | '/nuclear-medicine-therapies'
    | '/scan-centres'
    | '/scan-tests'
    | '/scan-centres/$city/$slug'
    | '/scan-tests/$modality/$detail'
    | '/scan-centres/$city'
    | '/scan-tests/$modality'
    | '/scan-centres/$city/area/$locality'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/advanced-cancer-imaging'
    | '/auth'
    | '/book-a-scan'
    | '/booking-confirmation'
    | '/compare-scans'
    | '/conditions'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/grievance'
    | '/lu-177-psma-therapy'
    | '/nuclear-medicine-therapies'
    | '/preparation-guides'
    | '/privacy'
    | '/refund-cancellation'
    | '/scan-centres'
    | '/scan-cost'
    | '/scan-tests'
    | '/terms'
    | '/_authenticated/admin'
    | '/conditions/$slug'
    | '/guides/$slug'
    | '/nuclear-medicine-therapies/$therapy'
    | '/scan-centres/$city'
    | '/scan-tests/$modality'
    | '/nuclear-medicine-therapies/'
    | '/scan-centres/'
    | '/scan-tests/'
    | '/scan-centres/$city/$slug'
    | '/scan-tests/$modality/$detail'
    | '/scan-centres/$city/'
    | '/scan-tests/$modality/'
    | '/scan-centres/$city/area/$locality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdvancedCancerImagingRoute: typeof AdvancedCancerImagingRoute
  AuthRoute: typeof AuthRoute
  BookAScanRoute: typeof BookAScanRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  CompareScansRoute: typeof CompareScansRoute
  ConditionsRoute: typeof ConditionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GrievanceRoute: typeof GrievanceRoute
  Lu177PsmaTherapyRoute: typeof Lu177PsmaTherapyRoute
  NuclearMedicineTherapiesRoute: typeof NuclearMedicineTherapiesRouteWithChildren
  PreparationGuidesRoute: typeof PreparationGuidesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundCancellationRoute: typeof RefundCancellationRoute
  ScanCentresRoute: typeof ScanCentresRouteWithChildren
  ScanCostRoute: typeof ScanCostRoute
  ScanTestsRoute: typeof ScanTestsRouteWithChildren
  TermsRoute: typeof TermsRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-cancer-imaging': {
      id: '/advanced-cancer-imaging'
      path: '/advanced-cancer-imaging'
      fullPath: '/advanced-cancer-imaging'
      preLoaderRoute: typeof AdvancedCancerImagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-a-scan': {
      id: '/book-a-scan'
      path: '/book-a-scan'
      fullPath: '/book-a-scan'
      preLoaderRoute: typeof BookAScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation': {
      id: '/booking-confirmation'
      path: '/booking-confirmation'
      fullPath: '/booking-confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-scans': {
      id: '/compare-scans'
      path: '/compare-scans'
      fullPath: '/compare-scans'
      preLoaderRoute: typeof CompareScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lu-177-psma-therapy': {
      id: '/lu-177-psma-therapy'
      path: '/lu-177-psma-therapy'
      fullPath: '/lu-177-psma-therapy'
      preLoaderRoute: typeof Lu177PsmaTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuclear-medicine-therapies': {
      id: '/nuclear-medicine-therapies'
      path: '/nuclear-medicine-therapies'
      fullPath: '/nuclear-medicine-therapies'
      preLoaderRoute: typeof NuclearMedicineTherapiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation-guides': {
      id: '/preparation-guides'
      path: '/preparation-guides'
      fullPath: '/preparation-guides'
      preLoaderRoute: typeof PreparationGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-cancellation': {
      id: '/refund-cancellation'
      path: '/refund-cancellation'
      fullPath: '/refund-cancellation'
      preLoaderRoute: typeof RefundCancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-centres': {
      id: '/scan-centres'
      path: '/scan-centres'
      fullPath: '/scan-centres'
      preLoaderRoute: typeof ScanCentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-cost': {
      id: '/scan-cost'
      path: '/scan-cost'
      fullPath: '/scan-cost'
      preLoaderRoute: typeof ScanCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-tests': {
      id: '/scan-tests'
      path: '/scan-tests'
      fullPath: '/scan-tests'
      preLoaderRoute: typeof ScanTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof ConditionsRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuclear-medicine-therapies/': {
      id: '/nuclear-medicine-therapies/'
      path: '/'
      fullPath: '/nuclear-medicine-therapies/'
      preLoaderRoute: typeof NuclearMedicineTherapiesIndexRouteImport
      parentRoute: typeof NuclearMedicineTherapiesRoute
    }
    '/nuclear-medicine-therapies/$therapy': {
      id: '/nuclear-medicine-therapies/$therapy'
      path: '/$therapy'
      fullPath: '/nuclear-medicine-therapies/$therapy'
      preLoaderRoute: typeof NuclearMedicineTherapiesTherapyRouteImport
      parentRoute: typeof NuclearMedicineTherapiesRoute
    }
    '/scan-centres/': {
      id: '/scan-centres/'
      path: '/'
      fullPath: '/scan-centres/'
      preLoaderRoute: typeof ScanCentresIndexRouteImport
      parentRoute: typeof ScanCentresRoute
    }
    '/scan-centres/$city': {
      id: '/scan-centres/$city'
      path: '/$city'
      fullPath: '/scan-centres/$city'
      preLoaderRoute: typeof ScanCentresCityRouteImport
      parentRoute: typeof ScanCentresRoute
    }
    '/scan-tests/': {
      id: '/scan-tests/'
      path: '/'
      fullPath: '/scan-tests/'
      preLoaderRoute: typeof ScanTestsIndexRouteImport
      parentRoute: typeof ScanTestsRoute
    }
    '/scan-tests/$modality': {
      id: '/scan-tests/$modality'
      path: '/$modality'
      fullPath: '/scan-tests/$modality'
      preLoaderRoute: typeof ScanTestsModalityRouteImport
      parentRoute: typeof ScanTestsRoute
    }
    '/scan-centres/$city/': {
      id: '/scan-centres/$city/'
      path: '/'
      fullPath: '/scan-centres/$city/'
      preLoaderRoute: typeof ScanCentresCityIndexRouteImport
      parentRoute: typeof ScanCentresCityRoute
    }
    '/scan-centres/$city/$slug': {
      id: '/scan-centres/$city/$slug'
      path: '/$slug'
      fullPath: '/scan-centres/$city/$slug'
      preLoaderRoute: typeof ScanCentresCitySlugRouteImport
      parentRoute: typeof ScanCentresCityRoute
    }
    '/scan-tests/$modality/': {
      id: '/scan-tests/$modality/'
      path: '/'
      fullPath: '/scan-tests/$modality/'
      preLoaderRoute: typeof ScanTestsModalityIndexRouteImport
      parentRoute: typeof ScanTestsModalityRoute
    }
    '/scan-tests/$modality/$detail': {
      id: '/scan-tests/$modality/$detail'
      path: '/$detail'
      fullPath: '/scan-tests/$modality/$detail'
      preLoaderRoute: typeof ScanTestsModalityDetailRouteImport
      parentRoute: typeof ScanTestsModalityRoute
    }
    '/scan-centres/$city/area/$locality': {
      id: '/scan-centres/$city/area/$locality'
      path: '/area/$locality'
      fullPath: '/scan-centres/$city/area/$locality'
      preLoaderRoute: typeof ScanCentresCityAreaLocalityRouteImport
      parentRoute: typeof ScanCentresCityRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConditionsRouteChildren {
  ConditionsSlugRoute: typeof ConditionsSlugRoute
}

const ConditionsRouteChildren: ConditionsRouteChildren = {
  ConditionsSlugRoute: ConditionsSlugRoute,
}

const ConditionsRouteWithChildren = ConditionsRoute._addFileChildren(
  ConditionsRouteChildren,
)

interface NuclearMedicineTherapiesRouteChildren {
  NuclearMedicineTherapiesTherapyRoute: typeof NuclearMedicineTherapiesTherapyRoute
  NuclearMedicineTherapiesIndexRoute: typeof NuclearMedicineTherapiesIndexRoute
}

const NuclearMedicineTherapiesRouteChildren: NuclearMedicineTherapiesRouteChildren =
  {
    NuclearMedicineTherapiesTherapyRoute: NuclearMedicineTherapiesTherapyRoute,
    NuclearMedicineTherapiesIndexRoute: NuclearMedicineTherapiesIndexRoute,
  }

const NuclearMedicineTherapiesRouteWithChildren =
  NuclearMedicineTherapiesRoute._addFileChildren(
    NuclearMedicineTherapiesRouteChildren,
  )

interface ScanCentresCityRouteChildren {
  ScanCentresCitySlugRoute: typeof ScanCentresCitySlugRoute
  ScanCentresCityIndexRoute: typeof ScanCentresCityIndexRoute
  ScanCentresCityAreaLocalityRoute: typeof ScanCentresCityAreaLocalityRoute
}

const ScanCentresCityRouteChildren: ScanCentresCityRouteChildren = {
  ScanCentresCitySlugRoute: ScanCentresCitySlugRoute,
  ScanCentresCityIndexRoute: ScanCentresCityIndexRoute,
  ScanCentresCityAreaLocalityRoute: ScanCentresCityAreaLocalityRoute,
}

const ScanCentresCityRouteWithChildren = ScanCentresCityRoute._addFileChildren(
  ScanCentresCityRouteChildren,
)

interface ScanCentresRouteChildren {
  ScanCentresCityRoute: typeof ScanCentresCityRouteWithChildren
  ScanCentresIndexRoute: typeof ScanCentresIndexRoute
}

const ScanCentresRouteChildren: ScanCentresRouteChildren = {
  ScanCentresCityRoute: ScanCentresCityRouteWithChildren,
  ScanCentresIndexRoute: ScanCentresIndexRoute,
}

const ScanCentresRouteWithChildren = ScanCentresRoute._addFileChildren(
  ScanCentresRouteChildren,
)

interface ScanTestsModalityRouteChildren {
  ScanTestsModalityDetailRoute: typeof ScanTestsModalityDetailRoute
  ScanTestsModalityIndexRoute: typeof ScanTestsModalityIndexRoute
}

const ScanTestsModalityRouteChildren: ScanTestsModalityRouteChildren = {
  ScanTestsModalityDetailRoute: ScanTestsModalityDetailRoute,
  ScanTestsModalityIndexRoute: ScanTestsModalityIndexRoute,
}

const ScanTestsModalityRouteWithChildren =
  ScanTestsModalityRoute._addFileChildren(ScanTestsModalityRouteChildren)

interface ScanTestsRouteChildren {
  ScanTestsModalityRoute: typeof ScanTestsModalityRouteWithChildren
  ScanTestsIndexRoute: typeof ScanTestsIndexRoute
}

const ScanTestsRouteChildren: ScanTestsRouteChildren = {
  ScanTestsModalityRoute: ScanTestsModalityRouteWithChildren,
  ScanTestsIndexRoute: ScanTestsIndexRoute,
}

const ScanTestsRouteWithChildren = ScanTestsRoute._addFileChildren(
  ScanTestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdvancedCancerImagingRoute: AdvancedCancerImagingRoute,
  AuthRoute: AuthRoute,
  BookAScanRoute: BookAScanRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  CompareScansRoute: CompareScansRoute,
  ConditionsRoute: ConditionsRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  GrievanceRoute: GrievanceRoute,
  Lu177PsmaTherapyRoute: Lu177PsmaTherapyRoute,
  NuclearMedicineTherapiesRoute: NuclearMedicineTherapiesRouteWithChildren,
  PreparationGuidesRoute: PreparationGuidesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundCancellationRoute: RefundCancellationRoute,
  ScanCentresRoute: ScanCentresRouteWithChildren,
  ScanCostRoute: ScanCostRoute,
  ScanTestsRoute: ScanTestsRouteWithChildren,
  TermsRoute: TermsRoute,
  GuidesSlugRoute: GuidesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
