CREATE TABLE public.nuclear_medicine_therapies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  short_name text NOT NULL,
  aliases text[] NOT NULL DEFAULT '{}',
  summary text NOT NULL,
  introduction text NOT NULL,
  what_it_is text NOT NULL,
  who_may_be_considered text NOT NULL,
  suitability_assessment text NOT NULL,
  reports_and_scans text[] NOT NULL DEFAULT '{}',
  treatment_process text[] NOT NULL DEFAULT '{}',
  preparation_guidance text NOT NULL,
  attendance_guidance text NOT NULL,
  side_effects_precautions text NOT NULL,
  follow_up_monitoring text NOT NULL,
  cost_factors text NOT NULL,
  related_scans jsonb NOT NULL DEFAULT '[]'::jsonb,
  faqs jsonb NOT NULL DEFAULT '[]'::jsonb,
  featured boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  published boolean NOT NULL DEFAULT false,
  clinical_reviewer text,
  clinical_reviewed_at date,
  seo_title text NOT NULL,
  seo_description text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT therapy_content_lengths CHECK (char_length(slug) BETWEEN 3 AND 100 AND char_length(name) BETWEEN 3 AND 180)
);
GRANT SELECT ON public.nuclear_medicine_therapies TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.nuclear_medicine_therapies TO authenticated;
GRANT ALL ON public.nuclear_medicine_therapies TO service_role;
ALTER TABLE public.nuclear_medicine_therapies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Published therapies are public" ON public.nuclear_medicine_therapies FOR SELECT TO anon, authenticated USING (published OR private.has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins manage therapies" ON public.nuclear_medicine_therapies FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin'::app_role)) WITH CHECK (private.has_role(auth.uid(), 'admin'::app_role));
CREATE TRIGGER nuclear_medicine_therapies_updated BEFORE UPDATE ON public.nuclear_medicine_therapies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.therapy_centre_availability (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  therapy_id uuid NOT NULL REFERENCES public.nuclear_medicine_therapies(id) ON DELETE CASCADE,
  centre_id uuid REFERENCES public.centres(id) ON DELETE SET NULL,
  centre_name text NOT NULL,
  city text NOT NULL,
  locality text NOT NULL DEFAULT '',
  availability_notes text NOT NULL DEFAULT '',
  confirmed boolean NOT NULL DEFAULT false,
  confirmed_at timestamptz,
  published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (therapy_id, centre_name, city, locality),
  CONSTRAINT therapy_availability_confirmation CHECK (NOT confirmed OR confirmed_at IS NOT NULL)
);
GRANT SELECT ON public.therapy_centre_availability TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.therapy_centre_availability TO authenticated;
GRANT ALL ON public.therapy_centre_availability TO service_role;
ALTER TABLE public.therapy_centre_availability ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Confirmed therapy availability is public" ON public.therapy_centre_availability FOR SELECT TO anon, authenticated USING ((published AND confirmed) OR private.has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins manage therapy availability" ON public.therapy_centre_availability FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin'::app_role)) WITH CHECK (private.has_role(auth.uid(), 'admin'::app_role));
CREATE TRIGGER therapy_centre_availability_updated BEFORE UPDATE ON public.therapy_centre_availability FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.therapy_prices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  therapy_id uuid NOT NULL REFERENCES public.nuclear_medicine_therapies(id) ON DELETE CASCADE,
  availability_id uuid REFERENCES public.therapy_centre_availability(id) ON DELETE CASCADE,
  centre_name text NOT NULL,
  city text NOT NULL,
  pricing_basis text NOT NULL,
  price_min_inr integer,
  price_max_inr integer,
  regular_price_inr integer,
  discount_amount_inr integer,
  discount_percent integer,
  inclusions text[] NOT NULL DEFAULT '{}',
  exclusions text[] NOT NULL DEFAULT '{}',
  valid_until date,
  last_updated date NOT NULL DEFAULT CURRENT_DATE,
  verified boolean NOT NULL DEFAULT false,
  verified_at timestamptz,
  published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT therapy_price_range CHECK ((price_min_inr IS NULL OR price_min_inr > 0) AND (price_max_inr IS NULL OR price_max_inr >= price_min_inr)),
  CONSTRAINT therapy_discount_values CHECK ((discount_amount_inr IS NULL OR discount_amount_inr >= 0) AND (discount_percent IS NULL OR discount_percent BETWEEN 0 AND 100)),
  CONSTRAINT therapy_price_verification CHECK (NOT verified OR (verified_at IS NOT NULL AND price_min_inr IS NOT NULL))
);
GRANT SELECT ON public.therapy_prices TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.therapy_prices TO authenticated;
GRANT ALL ON public.therapy_prices TO service_role;
ALTER TABLE public.therapy_prices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Verified therapy prices are public" ON public.therapy_prices FOR SELECT TO anon, authenticated USING ((published AND verified AND (valid_until IS NULL OR valid_until >= CURRENT_DATE)) OR private.has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Admins manage therapy prices" ON public.therapy_prices FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'admin'::app_role)) WITH CHECK (private.has_role(auth.uid(), 'admin'::app_role));
CREATE TRIGGER therapy_prices_updated BEFORE UPDATE ON public.therapy_prices FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.enquiries
  ADD COLUMN therapy_slug text,
  ADD COLUMN preferred_callback_time text,
  ADD COLUMN enquiry_kind text NOT NULL DEFAULT 'scan',
  ADD COLUMN campaign_attribution jsonb;

CREATE INDEX nuclear_medicine_therapies_public_order_idx ON public.nuclear_medicine_therapies (published, display_order);
CREATE INDEX therapy_availability_public_idx ON public.therapy_centre_availability (therapy_id, confirmed, published, city);
CREATE INDEX therapy_prices_public_idx ON public.therapy_prices (therapy_id, verified, published, valid_until);
CREATE INDEX enquiries_therapy_idx ON public.enquiries (therapy_slug, created_at DESC);

INSERT INTO public.nuclear_medicine_therapies (slug,name,short_name,aliases,summary,introduction,what_it_is,who_may_be_considered,suitability_assessment,reports_and_scans,treatment_process,preparation_guidance,attendance_guidance,side_effects_precautions,follow_up_monitoring,cost_factors,related_scans,faqs,featured,display_order,published,seo_title,seo_description) VALUES
('lu-177-psma-therapy','Lu-177 PSMA Therapy','Lu-177 PSMA','{"Lutetium-177 PSMA therapy","PSMA radioligand therapy"}','Targeted radioligand therapy assessment for selected patients with advanced PSMA-positive prostate cancer.','Lu-177 PSMA therapy is considered within specialist-led prostate cancer care after review of disease characteristics, prior treatment and overall health.','A PSMA-targeting molecule carries lutetium-177 radiation to PSMA-expressing cells. It is delivered only at appropriately licensed treatment centres.','Selected patients with advanced prostate cancer may be referred for assessment; a scan result alone does not establish suitability.','A nuclear medicine specialist coordinates with the treating oncologist and reviews PSMA expression, prior therapies, blood counts, kidney function, symptoms and treatment goals.','{"PSMA PET-CT","Pathology report","PSA trend","Prior treatment summary","Recent blood and kidney-function tests"}','{"Specialist referral and record review","Suitability and radiation-safety assessment","Centre-specific planning and informed consent","Administration at a licensed centre","Centre-directed monitoring and follow-up"}','The treating centre may request hydration, medicines review and recent laboratory tests. Follow only the individual instructions issued after assessment.','The centre decides whether same-day discharge or observation/admission is appropriate based on its protocol and the patient’s circumstances.','Temporary nausea, fatigue, dry mouth or blood-count changes may occur. The treating team explains individual risks and radiation-safety precautions.','The treating team may monitor symptoms, PSA, blood counts, kidney function and imaging as clinically appropriate.','Radiopharmaceutical supply, prescribed activity, number of cycles, hospital protocol, tests, observation or admission and supportive care can affect the estimate.','[{"label":"PSMA PET-CT","to":"/scan-tests/pet-ct-scan/psma-pet-ct"}]','[{"question":"Does a positive PSMA PET-CT guarantee treatment eligibility?","answer":"No. Specialists assess scan findings together with prior treatment, blood tests, kidney function, symptoms and overall health."},{"question":"Is the estimate for one cycle or the full course?","answer":"The pricing basis must be stated by the selected centre. Ask whether an estimate covers one administration, one cycle or the planned course."}]',true,1,true,'Lu-177 PSMA Therapy Assistance Delhi NCR | SavoScan','Explore Lu-177 PSMA therapy assessment, centre options and personalised treatment estimates across Delhi NCR.'),
('lu-177-dotatate-prrt','Lu-177 DOTATATE Therapy / PRRT','Lu-177 DOTATATE / PRRT','{"Lu-177 DOTA therapy","Peptide receptor radionuclide therapy","PRRT"}','Peptide receptor radionuclide therapy assessment for selected patients with somatostatin-receptor-positive neuroendocrine tumours.','Lu-177 DOTATATE therapy, commonly called PRRT, is a specialist radionuclide treatment considered for selected neuroendocrine tumours.','A somatostatin-analogue carrier delivers lutetium-177 radiation to tumour cells expressing suitable receptors. “Lu-177 DOTA therapy” is a related search term; the actual treatment and radiopharmaceutical are confirmed by the specialist.','Patients with selected neuroendocrine tumours may be referred after receptor imaging and multidisciplinary review.','Specialists review receptor expression, tumour type and distribution, prior treatments, blood counts, kidney and liver function and the goals of care.','{"DOTATATE or DOTANOC PET-CT","Histopathology","Prior imaging","Treatment summary","Recent blood, kidney and liver tests"}','{"Referral and receptor-imaging review","Laboratory and clinical assessment","Centre planning and kidney-protection protocol","Licensed-centre administration","Planned follow-up and cycle review"}','The centre may provide fasting, hydration, medicine and amino-acid infusion instructions. These are patient- and centre-specific.','Treatment may be outpatient or may require observation/admission depending on centre protocol, patient condition and local radiation-safety requirements.','Nausea, fatigue, temporary blood-count changes and kidney-related risks may be discussed. Individual precautions come from the treating team.','Blood counts, kidney/liver function, symptoms and imaging may be reviewed before later cycles and during follow-up.','Radiopharmaceutical, amino-acid infusion, prescribed cycles, tests, admission/observation and centre protocol influence cost.','[{"label":"DOTATATE / DOTANOC PET-CT","to":"/scan-tests/pet-ct-scan"}]','[{"question":"Is Lu-177 DOTA therapy the same as PRRT?","answer":"The phrase is often used broadly. The nuclear medicine specialist confirms the actual receptor-targeted treatment and radiopharmaceutical."},{"question":"Is receptor imaging required?","answer":"Relevant imaging may be reviewed, but the treating specialist determines which scans and reports are required."}]',true,2,true,'Lu-177 DOTATATE PRRT Assistance Delhi NCR | SavoScan','Understand Lu-177 DOTATATE PRRT assessment and request centre options and personalised estimates in Delhi NCR.'),
('radioiodine-thyroid-cancer','Radioiodine / I-131 Therapy for Thyroid Cancer','I-131 for Thyroid Cancer','{"Radioiodine therapy thyroid cancer","RAI thyroid cancer","I-131 therapy"}','Radioiodine treatment assessment for selected differentiated thyroid cancers.','Radioiodine therapy may be considered after specialist review for selected differentiated thyroid cancers, often within a pathway involving thyroid surgery and follow-up.','Iodine-131 is taken up by suitable thyroid tissue. The prescribed activity and purpose are determined by the treating nuclear medicine and thyroid-care team.','Selected patients with differentiated thyroid cancer may be considered; not every thyroid cancer type takes up radioiodine.','Specialists review pathology, surgery details, staging, thyroid tests, prior imaging, pregnancy/breastfeeding status and treatment goals.','{"Histopathology","Operative summary","Thyroglobulin and thyroid tests","Prior ultrasound or nuclear medicine imaging","Pregnancy testing when applicable"}','{"Post-surgery specialist review","Preparation strategy and laboratory review","Prescribed I-131 administration","Radiation-safety instructions and discharge planning","Thyroid-cancer follow-up"}','Preparation may involve thyroid-hormone management or stimulation and a low-iodine diet. The treating centre provides the exact plan; do not alter medicines without medical advice.','Admission or protected-room requirements depend on the prescribed activity, regulations and centre protocol.','Temporary neck discomfort, taste change, nausea, salivary-gland symptoms or dry mouth may occur. Pregnancy and breastfeeding restrictions are essential and centre-led.','Follow-up may include thyroid tests, thyroglobulin, specialist examination and imaging as selected by the treating team.','Prescribed activity, inpatient requirements, room category, laboratory tests, imaging and follow-up services affect the estimate.','[{"label":"Nuclear medicine scans","to":"/scan-tests/gamma-camera-spect"}]','[{"question":"Are all thyroid cancers treated with radioiodine?","answer":"No. Suitability depends on the cancer type, pathology, stage and specialist assessment."},{"question":"Will admission be required?","answer":"That depends on the prescribed activity, centre protocol and radiation-safety requirements."}]',true,3,true,'I-131 Radioiodine Therapy for Thyroid Cancer | SavoScan','Explore radioiodine therapy assessment for selected thyroid cancers and request Delhi NCR centre and estimate assistance.'),
('radioiodine-hyperthyroidism','Radioiodine / I-131 Therapy for Hyperthyroidism','I-131 for Hyperthyroidism','{"Radioiodine for overactive thyroid","RAI hyperthyroidism"}','Radioiodine treatment assessment for an overactive thyroid, kept separate from thyroid-cancer treatment.','I-131 therapy can be considered for selected people with hyperthyroidism after endocrine and nuclear medicine assessment.','A prescribed amount of iodine-131 is taken up by active thyroid tissue to reduce thyroid activity over time. This pathway differs from thyroid-cancer treatment.','People with selected causes of hyperthyroidism may be referred; pregnancy and breastfeeding are contraindications and individual factors matter.','The team reviews the cause and severity of hyperthyroidism, thyroid tests, medicines, uptake/imaging where needed, eye disease, pregnancy status and other health factors.','{"Thyroid function tests","Endocrinology notes","Thyroid uptake or scan if requested","Ultrasound if relevant","Medicine list"}','{"Endocrine and nuclear medicine review","Medicine and pregnancy-safety review","Centre-specific preparation","Oral I-131 administration","Thyroid-function follow-up"}','Medication changes and dietary instructions vary. Follow the treating doctor’s plan and do not stop antithyroid medicine without instruction.','This is often delivered without overnight admission, but the selected centre confirms attendance and discharge requirements.','Temporary neck discomfort or a short-term change in thyroid symptoms can occur. Later underactive thyroid is common and requires monitoring and treatment when indicated.','Thyroid function is checked over time; the treating clinician adjusts medicines and assesses response.','Prescribed activity, consultation, uptake testing or imaging, laboratory tests and centre services affect the estimate.','[{"label":"Nuclear medicine scans","to":"/scan-tests/gamma-camera-spect"}]','[{"question":"Is this the same treatment as I-131 for thyroid cancer?","answer":"No. The purpose, activity, preparation and follow-up pathway are different."},{"question":"How quickly does thyroid function change?","answer":"The response develops over time. Your treating clinician schedules blood tests and advises on medicines."}]',true,4,true,'Radioiodine Therapy for Hyperthyroidism Delhi NCR | SavoScan','Learn about I-131 assessment for hyperthyroidism and request centre options and treatment estimates across Delhi NCR.'),
('i-131-mibg-therapy','I-131 MIBG Therapy','I-131 MIBG','{"MIBG radionuclide therapy"}','Specialist-targeted radionuclide therapy assessment for selected MIBG-avid tumours.','I-131 MIBG therapy is considered in selected specialist oncology pathways when tumour biology and imaging support assessment.','MIBG carries iodine-131 to suitable cells that take up the compound. Treatment requires a licensed centre with specialist and radiation-safety facilities.','Selected patients with MIBG-avid tumours may be assessed after oncology and nuclear medicine review.','Assessment can include diagnostic MIBG imaging, pathology, disease extent, prior treatments, blood counts, kidney/liver function and thyroid protection planning.','{"Diagnostic MIBG imaging","Histopathology","Prior imaging","Treatment history","Recent blood, kidney and liver tests"}','{"Specialist referral","MIBG-avidity and organ-function review","Thyroid-protection and centre planning","Licensed-centre administration","Monitoring and follow-up"}','The centre provides medicine-interaction, thyroid-blocking, hydration and laboratory instructions specific to the patient.','Protected-room admission is commonly considered, but duration and requirements are determined by the treating centre.','Nausea, fatigue, blood-pressure changes, thyroid exposure and delayed blood-count effects may be discussed. Follow centre-issued precautions.','The team may monitor blood counts, organ function, symptoms and imaging over an individual schedule.','Radiopharmaceutical, prescribed activity, inpatient stay, monitoring, medicines and number of administrations affect cost.','[{"label":"Nuclear medicine scans","to":"/scan-tests/gamma-camera-spect"}]','[{"question":"Does MIBG imaging confirm treatment suitability?","answer":"It is one part of assessment. Specialists also review tumour type, prior treatment, organ function and overall condition."},{"question":"Is hospital admission always required?","answer":"The treating centre determines this from the prescribed activity, facilities and patient-specific needs."}]',false,5,true,'I-131 MIBG Therapy Assistance Delhi NCR | SavoScan','Request specialist-centre options and personalised I-131 MIBG therapy estimate assistance in Delhi NCR.'),
('y-90-radioembolization','Y-90 Radioembolization / TARE / SIRT','Y-90 Radioembolization','{"TARE","SIRT","Yttrium-90 radioembolization"}','A combined interventional radiology and nuclear medicine pathway for selected liver tumours.','Y-90 radioembolization, also called TARE or SIRT, is a specialist liver-directed treatment requiring coordinated assessment and planning.','Tiny microspheres carrying yttrium-90 are delivered through liver arteries by an interventional radiologist after detailed mapping and safety assessment.','Selected patients with primary or metastatic liver tumours may be referred after multidisciplinary review.','Assessment includes liver function, vessel anatomy, tumour distribution, performance status, prior treatment and a planning angiogram with shunt evaluation.','{"Liver CT or MRI","PET-CT where relevant","Liver-function and blood tests","Oncology summary","Mapping angiography and shunt study"}','{"Multidisciplinary review","Planning angiogram and safety mapping","Dosimetry and treatment planning","Y-90 administration by the specialist team","Post-treatment monitoring and imaging"}','The centre provides fasting, medicines, contrast-safety and procedure instructions. Blood-thinner changes must only follow medical advice.','Day-care observation or admission may be required based on the procedure, access-site recovery and clinical condition.','Fatigue, abdominal discomfort, nausea, fever or appetite change can occur; uncommon serious liver, gastrointestinal or lung complications are discussed during consent.','The team monitors symptoms, liver function and follow-up imaging according to the treatment plan.','Mapping, angiography, dosimetry, microspheres, interventional facilities, admission and follow-up imaging affect the estimate.','[{"label":"PET-CT imaging","to":"/scan-tests/pet-ct-scan"},{"label":"CT imaging","to":"/scan-tests/ct-scan"},{"label":"MRI imaging","to":"/scan-tests/mri-scan"}]','[{"question":"Why is a planning angiogram needed?","answer":"It maps the blood supply and helps the specialist assess safe delivery and calculate treatment planning."},{"question":"Is TARE a nuclear medicine scan?","answer":"No. It is a treatment pathway combining interventional radiology and radionuclide therapy expertise."}]',false,6,true,'Y-90 Radioembolization TARE SIRT Assistance | SavoScan','Explore Y-90 radioembolization assessment and request specialist centre and estimate support across Delhi NCR.'),
('bone-pain-palliation','Radionuclide Therapy for Bone Pain Palliation','Bone Pain Palliation','{"Radionuclide bone pain therapy"}','Radionuclide treatment intended to help relieve pain in selected patients with painful bone metastases.','Bone pain palliation uses a bone-seeking radiopharmaceutical in selected patients to support symptom relief as part of palliative cancer care.','The radiopharmaceutical concentrates in suitable active bone sites and delivers radiation locally. The purpose is symptom relief, not a cure claim.','Selected patients with painful bone metastases may be assessed when imaging, blood counts, kidney function and the wider pain-management plan are appropriate.','Nuclear medicine and oncology teams review pain pattern, imaging, marrow reserve, kidney function, recent treatments and current medicines.','{"Bone scan or relevant PET imaging","Recent blood counts","Kidney-function tests","Oncology treatment summary","Pain and medicine history"}','{"Referral and symptom review","Imaging and laboratory assessment","Radiopharmaceutical selection and consent","Administration at a licensed centre","Pain, blood-count and clinical follow-up"}','The centre provides hydration, medicine and laboratory instructions based on the chosen radiopharmaceutical and patient condition.','Many administrations are outpatient, but the centre confirms observation or admission requirements.','A temporary pain flare and delayed blood-count reduction may occur. The treating team explains precautions and how this fits with other pain treatments.','Pain response, medicine needs and blood counts may be followed; timing and benefit vary between patients.','Radiopharmaceutical choice, administered activity, tests, centre fees and follow-up influence the estimate.','[{"label":"Bone scan and SPECT","to":"/scan-tests/gamma-camera-spect"}]','[{"question":"Is this treatment intended to cure cancer?","answer":"No. Its purpose is symptom relief in selected patients as part of a broader palliative-care plan."},{"question":"Can pain medicines continue?","answer":"The treating team reviews current medicines and advises what to continue or change."}]',false,7,true,'Radionuclide Bone Pain Palliation Assistance | SavoScan','Understand radionuclide therapy for bone pain palliation and request Delhi NCR centre and cost assistance.'),
('radium-223-therapy','Radium-223 Therapy','Radium-223','{"Ra-223 therapy"}','Targeted alpha therapy assessment for selected prostate cancer patients with symptomatic bone-predominant disease.','Radium-223 is a specialist radionuclide treatment with a distinct indication and pathway from general bone pain palliation.','Radium-223 behaves similarly to calcium and targets areas of increased bone turnover, delivering short-range alpha radiation.','Selected patients with advanced prostate cancer and appropriate bone-dominant disease may be referred after oncology and nuclear medicine review.','The team reviews disease distribution, symptoms, blood counts, prior and current treatments, fracture risk and overall clinical goals.','{"Relevant bone or PET imaging","Recent blood counts","Prostate cancer treatment summary","PSA and clinical history","Medicine list"}','{"Oncology and nuclear medicine review","Blood-count and imaging assessment","Treatment scheduling and consent","Series of centre-based administrations","Blood and symptom monitoring"}','Recent blood tests are required and medicine or bone-health plans may be reviewed. Follow the centre’s exact instructions.','Administration is commonly outpatient, subject to the patient’s condition and centre protocol.','Diarrhoea, nausea, fatigue and blood-count suppression may occur. The team reviews marrow reserve, fracture risk and treatment combinations.','Blood counts and symptoms are checked during the course; oncology follow-up continues alongside treatment.','Number of administrations, radiopharmaceutical, laboratory monitoring, consultations and centre charges affect the estimated course cost.','[{"label":"Bone scan and SPECT","to":"/scan-tests/gamma-camera-spect"},{"label":"PSMA PET-CT","to":"/scan-tests/pet-ct-scan/psma-pet-ct"}]','[{"question":"Is Radium-223 the same as general bone pain palliation?","answer":"No. Radium-223 has a distinct specialist indication, assessment pathway and treatment course."},{"question":"Is the quoted cost per administration or full course?","answer":"Confirm the pricing basis. A complete planned course can involve multiple administrations."}]',false,8,true,'Radium-223 Therapy Assistance Delhi NCR | SavoScan','Explore Radium-223 assessment and request centre options and clearly labelled treatment estimates in Delhi NCR.'),
('radiosynovectomy','Radiosynovectomy / Radiosynoviorthesis','Radiosynovectomy','{"Radiosynoviorthesis","radionuclide joint therapy"}','Local radionuclide treatment assessment for selected persistent inflammatory joint conditions.','Radiosynovectomy, also called radiosynoviorthesis, is a specialist procedure considered for selected joints with persistent synovial inflammation.','A small amount of a selected radionuclide is administered into the joint by a qualified team to act on inflamed synovial tissue.','Patients with selected chronic inflammatory or recurrent joint synovitis may be referred after rheumatology, orthopaedic and nuclear medicine assessment.','The team confirms the diagnosis, joint involved, prior treatments, imaging, infection risk, bleeding risk, pregnancy status and expected benefit.','{"Joint ultrasound or MRI where requested","Rheumatology or orthopaedic notes","Prior treatment history","Relevant blood tests","Pregnancy testing when applicable"}','{"Specialist referral and joint assessment","Imaging and safety review","Radionuclide selection and consent","Image-guided joint administration where applicable","Immobilisation and follow-up plan"}','Medicine, fasting and joint-rest instructions vary by centre and joint. Blood-thinner changes require treating-clinician advice.','Usually a planned day-care procedure, but the centre determines observation and mobility arrangements.','Temporary joint discomfort or swelling can occur; infection, bleeding and radiation precautions are discussed before treatment.','The treating team reviews pain, swelling, function and any required imaging over time.','Joint, radionuclide, image guidance, specialist fees, day-care facilities and follow-up affect the estimate.','[{"label":"MRI imaging","to":"/scan-tests/mri-scan"},{"label":"Ultrasound imaging","to":"/scan-tests/ultrasound"}]','[{"question":"Is radiosynovectomy suitable for every painful joint?","answer":"No. It is considered for selected inflammatory joint conditions after specialist assessment."},{"question":"Will the joint need rest afterward?","answer":"The treating centre provides joint-specific mobility and aftercare instructions."}]',false,9,true,'Radiosynovectomy Radiosynoviorthesis Assistance | SavoScan','Learn about radiosynovectomy assessment and request specialist-centre and treatment-estimate support in Delhi NCR.');